name: Build and Release

on:
  push:
    branches:
      - main
      - pre_release

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    if     : github.event.head_commit.author.email != 'github-actions[bot]@users.noreply.github.com'
    outputs: 
      isPrerelease: ${{ steps.set_prerelease.outputs.isPrerelease }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install vsce
        run : npm install -g vsce

      - name: Install dependencies
        run : npm install

      - name: Commit all changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update files"

      - name: Determine release type
        id  : set_prerelease
        run : |
          if [[ "${{ github.ref }}" == "refs/heads/pre_release" ]]; then
            echo "::set-output name=isPrerelease::true"
          else
            echo "::set-output name=isPrerelease::false"
          fi

      - name: Bump version
        run : |
          if [[ "${{ steps.set_prerelease.outputs.isPrerelease }}" == "true" ]]; then
            npm version patch -m "Pre-release version %s"
          else
            npm version minor -m "Release version %s"
          fi

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push using SSH
        run: |
          git push git@github.com:usmanmehmood55/c-toolkit.git

      - name: Package Extension
        run : vsce package

      - name: Publish to Marketplace
        run : |
          if [[ "${{ steps.set_prerelease.outputs.isPrerelease }}" == "true" ]]; then
            vsce publish -p ${{ secrets.VSCE_PUBLISH_PAT }} --pre-release
          else
            vsce publish -p ${{ secrets.VSCE_PUBLISH_PAT }}
          fi

      - name: Get package information
        id  : package_info
        run : |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
          echo "::set-output name=name::$(node -p "require('./package.json').name")"
          echo "::set-output name=publisher::$(node -p "require('./package.json').publisher")"

      - name: Create Release
        id  : create_release
        uses: actions/create-release@v1
        with: 
          tag_name    : ${{ steps.package_info.outputs.version }}
          release_name: Release ${{ steps.package_info.outputs.version }}
          draft       : false
          prerelease  : ${{ steps.set_prerelease.outputs.isPrerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        id  : upload-release-asset
        uses: actions/upload-release-asset@v1
        with: 
          upload_url        : ${{ steps.create_release.outputs.upload_url }}
          asset_path        : ./${{ steps.package_info.outputs.name }}-${{ steps.package_info.outputs.version }}.vsix
          asset_name        : ${{ steps.package_info.outputs.name }}-${{ steps.package_info.outputs.version }}.vsix
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}