name: Build and Release

on:
  push:
    branches:
      - main
      - pre_release

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    if     : github.event.head_commit.author.email != 'github-actions[bot]@users.noreply.github.com'
    outputs: 
      isPrerelease: ${{ steps.set_prerelease.outputs.isPrerelease }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install vsce
        run: |
          npm install -g vsce

      - name: Validating VSCE PAT
        run: |
          echo "Checking VSCE_PUBLISH_PAT..."
          if ! vsce verify-pat -p ${{ secrets.VSCE_PUBLISH_PAT }}; then
            echo "VSCE_PUBLISH_PAT is invalid or expired."
            exit 1
          else
            echo "VSCE_PUBLISH_PAT is valid."
          fi

      - name: Validating GitHub PAT
        run: |
          echo "Checking PERSONAL_ACCESS_TOKEN..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/user)
          if [ "$response" -ne 200 ]; then
            echo "PERSONAL_ACCESS_TOKEN is invalid or expired."
            exit 1
          else
            echo "PERSONAL_ACCESS_TOKEN is valid."
          fi

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Determine release type
        id  : set_prerelease
        run : |
          if [[ "${{ github.ref }}" == "refs/heads/pre_release" ]]; then
            echo "::set-output name=isPrerelease::true"
            echo "PreRelease"
          else
            echo "::set-output name=isPrerelease::false"
            echo "Release"
          fi

      - name: Check for version bump
        id: check_version
        run: |
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq .version -r)
          CURRENT_VERSION=$(jq .version -r package.json)
          
          echo "Previous Version: $PREVIOUS_VERSION"
          echo "Current Version: $CURRENT_VERSION"

          if [[ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]]; then
            echo "::set-output name=version_bumped::true"
          else
            echo "::set-output name=version_bumped::false"
          fi

      - name: Package Extension
        if  : steps.check_version.outputs.version_bumped == 'true'
        run : vsce package

      - name: Publish to Marketplace
        if  : steps.check_version.outputs.version_bumped == 'true'
        run : |
          if [[ "${{ steps.set_prerelease.outputs.isPrerelease }}" == "true" ]]; then
            vsce publish -p ${{ secrets.VSCE_PUBLISH_PAT }} --pre-release
          else
            vsce publish -p ${{ secrets.VSCE_PUBLISH_PAT }}
          fi

      - name: Get package information
        if  : steps.check_version.outputs.version_bumped == 'true'
        id  : package_info
        run : |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
          echo "::set-output name=name::$(node -p "require('./package.json').name")"
          echo "::set-output name=publisher::$(node -p "require('./package.json').publisher")"

      - name: Create Release
        if  : steps.check_version.outputs.version_bumped == 'true'
        id  : create_release
        uses: actions/create-release@v1
        with: 
          tag_name    : ${{ steps.package_info.outputs.version }}
          release_name: Release ${{ steps.package_info.outputs.version }}
          draft       : false
          prerelease  : ${{ steps.set_prerelease.outputs.isPrerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        if  : steps.check_version.outputs.version_bumped == 'true'
        id  : upload-release-asset
        uses: actions/upload-release-asset@v1
        with: 
          upload_url        : ${{ steps.create_release.outputs.upload_url }}
          asset_path        : ./${{ steps.package_info.outputs.name }}-${{ steps.package_info.outputs.version }}.vsix
          asset_name        : ${{ steps.package_info.outputs.name }}-${{ steps.package_info.outputs.version }}.vsix
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}