name: Build and Release

on:
  push:
    branches:
      - main
      - pre_release

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    if     : github.event.head_commit.author.email != 'github-actions[bot]@users.noreply.github.com'
    permissions:
      contents: write
    outputs: 
      isPrerelease: ${{ steps.set_prerelease.outputs.isPrerelease }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install vsce
        run: |
          npm install -g @vscode/vsce

      - name: Validating VSCE PAT
        run: |
          echo "Checking VSCE_PUBLISH_PAT..."
          if ! vsce verify-pat -p ${{ secrets.VSCE_PUBLISH_PAT }} UsmanMehmood; then
            echo "VSCE_PUBLISH_PAT is invalid or expired."
            exit 1
          else
            echo "VSCE_PUBLISH_PAT is valid."
          fi

      - name: Validating GITHUB_TOKEN
        run: |
          echo "Checking GITHUB_TOKEN..."
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }})
          if [ "$response" -ne 200 ]; then
            echo "GITHUB_TOKEN is unavailable or invalid for this repository."
            exit 1
          else
            echo "GITHUB_TOKEN is valid."
          fi

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Determine release type
        id  : set_prerelease
        run : |
          if [[ "${{ github.ref }}" == "refs/heads/pre_release" ]]; then
            echo "isPrerelease=true" >> "$GITHUB_OUTPUT"
            echo "PreRelease"
          else
            echo "isPrerelease=false" >> "$GITHUB_OUTPUT"
            echo "Release"
          fi

      - name: Check for version bump
        id: check_version
        run: |
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq .version -r)
          CURRENT_VERSION=$(jq .version -r package.json)
          
          echo "Previous Version: $PREVIOUS_VERSION"
          echo "Current Version: $CURRENT_VERSION"

          if [[ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]]; then
            echo "version_bumped=true" >> "$GITHUB_OUTPUT"
          else
            echo "version_bumped=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Package Extension
        if  : steps.check_version.outputs.version_bumped == 'true'
        run : vsce package

      - name: Publish to Marketplace
        if  : steps.check_version.outputs.version_bumped == 'true'
        run : |
          if [[ "${{ steps.set_prerelease.outputs.isPrerelease }}" == "true" ]]; then
            vsce publish --pre-release
          else
            vsce publish
          fi
        env:
          VSCE_PAT: ${{ secrets.VSCE_PUBLISH_PAT }}

      - name: Get package information
        if  : steps.check_version.outputs.version_bumped == 'true'
        id  : package_info
        run : |
          echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
          echo "name=$(node -p "require('./package.json').name")" >> "$GITHUB_OUTPUT"
          echo "publisher=$(node -p "require('./package.json').publisher")" >> "$GITHUB_OUTPUT"

      - name: Create Release
        if  : steps.check_version.outputs.version_bumped == 'true'
        id  : create_release
        uses: softprops/action-gh-release@v2
        with: 
          tag_name    : ${{ steps.package_info.outputs.version }}
          name        : Release ${{ steps.package_info.outputs.version }}
          draft       : false
          prerelease  : ${{ steps.set_prerelease.outputs.isPrerelease == 'true' }}
          files       : ./${{ steps.package_info.outputs.name }}-${{ steps.package_info.outputs.version }}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
